default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: <%= ENV['RAILS_PG_HOST'] || 'localhost' %>

development:
  <<: *default
  database: postgres
  password: mysecretlocalpassword

test:
  <<: *default
  database: postgres
  password: mysecretlocalpassword

production:
  <<: *default
  database: postgres
  password: mysecretlocalpassword
